### ISSUE TITLE
Error parsing knots within uSpline

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#147]
I have reached a barrier with `uSpline`, and I am not sure whether it is intentional or not. To summarize: if I make my own vector of knots, I can tell `uSpline` to use that as the knots without issue. However, if I try pulling a vector from the data directly (via the `unique` function within base R), R doesn't recognize `uSpline` as a function.

Perhaps you intentionally require the user to input the knots as a "raw" vector -- if that is the case, it would be useful to throw an error pointing that out. (I had to do a bit of digging to uncover why the code was failing.)

Here is an example of the issue.

```
# setup
library(data.table)
library(ivmte)

set.seed(1001)
N <- 2000

dt <- data.table(
  id = 1:N,
  u = runif(N),
  z = sample(1:4, N, replace = T),
  epsilon = rnorm(N, sd = .1)
)

dt[, p := (z == 1)*0.12 + (z == 2)*0.29 + (z == 3)*0.48 + (z == 4)*0.78]
dt[, d := as.integer(u <= p)]
dt[, y0 := 0.9 - 1.1*u + 0.3*u^2]
dt[, y1 := 0.35 - 0.3*u - 0.05*u^2]
dt[, y := y1*d + y0*(1 - d) + epsilon]

args_test <- list(
  data = dt,
  propensity = d ~ factor(z),
  ivlike = c(y ~ d,
             y ~ d | factor(z)),
  m0 = ~u + I(u^2),
  target = "att",
  lpsolver = "gurobi"
)

# use p-score values as knots in the spline - pull directly from data
args_test$m1 <- ~uSplines(degree = 0, knots = unique(dt$p))
res.test <- do.call(ivmte, args_test)
```
```
 Error in uSplines(degree = 0, knots = unique(dt$p)) : 
  could not find function "uSplines" 
```
```
# use p-score values as knots in the spline - input as pre-processed vector
my_knots <- unique(dt$p)
args_test$m1 <- ~uSplines(degree = 0, knots = my_knots)
res.test <- do.call(ivmte, args_test)
# runs without error
```

**Comment by jkcshea** [comment]
Done!

The issue turned out to be much simpler than I realized.
The problem was with `dt$p`, in particular the `$` operator.
The parsing for `uSplines` was not accounting for operators.
This has now been corrected, so you can include `$`, `+`, `-`, `/`, `*`, and `^`.

**Comment by johnnybonney** [comment]
The problem still persists when the `uSplines` portion is interacted with another variable:

```
# setup
library(data.table)
library(ivmte)

set.seed(1001)
N <- 2000

dt <- data.table(
  id = 1:N,
  u = runif(N),
  x = sample(0:2, N, replace = T),
  z = sample(1:4, N, replace = T),
  epsilon = rnorm(N, sd = .1)
)

dt[, p := (z == 1)*0.12 + (z == 2)*0.29 + (z == 3)*0.48 + (z == 4)*0.78]
dt[, d := as.integer(u <= p)]
dt[, y0 := 0.9 - 1.1*u + 0.3*u^2]
dt[, y1 := 0.35 - 0.3*u - 0.05*u^2]
dt[, y := y1*d + y0*(1 - d) + epsilon]

args_test <- list(
  data = dt,
  propensity = d ~ factor(z),
  ivlike = c(y ~ d,
             y ~ d | factor(z)),
  m0 = ~u + I(u^2),
  target = "att",
  lpsolver = "gurobi"
)

# use p-score values as knots in the spline - pull directly from data
args_test$m1 <- ~factor(x):uSplines(degree = 0, knots = unique(dt$p))
res.test <- do.call(ivmte, args_test)
```
```
LP solver: Gurobi ('gurobi')

Obtaining propensity scores...
Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...
 Error in uSplines(degree = 0, knots = unique(dt$p)) : 
  could not find function "uSplines" 
```

**Comment by a-torgovitsky** [comment]
Just to clarify and make sure I understand the problem...
Is this an easy workaround?
```r
pscore.values <- unique(dt$p)
args_test$m1 <- ~factor(x):uSplines(degree = 0, knots = pscore.values)
```

Or is there something more fundamental going on?

**Comment by johnnybonney** [comment]
Yes, that is the exact workaround I have been using.

**Comment by jkcshea** [comment]
Ah sorry, I missed the part involving interactions.
Give it a shot now, interactions should be no problem.
